import { ic } from './icons.js'

export function referenceHelpHtml(){
  return `<p>References are optional lookup workbooks. They help you check existing assignments and review suggested corrections.</p>
    <h4>Milestone register</h4><p>Checks the L2 already assigned to equipment. When it identifies one matching milestone, it can suggest the full name or the L1 parent listed in the register. Missing or conflicting matches need review.</p>
    <p><b>It does not choose an equipment's L2</b> from its description or UPN, or prove that the existing L2 is suitable.</p>
    <h4>Item Master catalog</h4><p>Uses the selected current list to check Item Master names. It can suggest a VF equivalent when one name matches after accounting for the site prefix. A different prefix alone is not an error. Confirm the equipment and checklist requirements before replacing it.</p>
    <h4>How to use them</h4><ol><li>Choose a workbook and check the selected sheet. Use the milestone sheet with L2 entries and their L1 parents, or the sheet containing current Item Masters.</li><li>Select <b>Apply references</b> to rerun the audit. This does not apply corrections.</li><li>Open an action, check the issue and edit the suggested values if needed. Select <b>Review changes</b> to see the full change list, then <b>Apply changes</b> or <b>Cancel</b>.</li></ol>
    <p>Historical, obsolete and comment sheets are not used. Check any selection warning; remove a reference you do not need.</p>
    <p><b>Local and session-only.</b> Original workbooks stay unchanged. To load a saved review, first load the same registry and reference data. Changing references clears the current undo history.</p>
    <p>The completed registry in <b>Compare Projects</b> is separate. It provides comparison context, not replacement rules.</p>`;
}

export const GUIDE_SECTIONS=[
  {id:'start',label:'Getting started',icon:'upload',title:'Run your first audit',body:`
    <p>Start with an exported Cx Registry workbook. You do not need a MEL, cable schedule or another project to run the audit.</p>
    <ol><li>Choose <b>Choose workbook</b> or drop an .xlsx or .xls file into the upload area. The app identifies usable registry sheets.</li><li>Wait for the Dashboard. Processing time depends on the workbook and your device.</li><li>Work through <b>Invalid</b>, <b>Rule broken</b>, then <b>Check this</b>. Read Notes for useful context.</li><li>Use <b>Actions</b> to review findings and prepare corrections. Save your review before refreshing, closing, or loading another registry.</li></ol>
    <p>The original workbook is never changed. A draft in this app is not a change in Exto.</p>`},
  {id:'around',label:'The workspace',icon:'panel-left-open',title:'Find the right view',body:`
    <ul><li><b>Dashboard:</b> finding totals, milestone readiness, hierarchy health and checks. Click a summary to open its findings.</li><li><b>Audit Findings:</b> search and filter individual issues; open a row for the explanation and source location.</li><li><b>Actions:</b> review groups, preview corrections, record decisions and export your work.</li><li><b>SSM Hierarchy:</b> explore equipment placement in the current working draft.</li><li><b>Compare Projects:</b> compare structure against a completed project, system by system.</li><li><b>Completed Equipment:</b> appears when the registry has a recognized Equipment Status Report. Matched completed equipment is set aside from active audit metrics.</li><li><b>Rules:</b> plain-language checks, examples and switches.</li></ul>
    <p>Collapse the left menu for more space. Views that offer a full-screen button can be expanded and restored.</p>`},
  {id:'severity',label:'Finding levels',icon:'triangle-alert',title:'Understand the priority',body:`
    <ul><li><b>Invalid:</b> an identity, reference or approved-value conflict, such as duplicate tags, an unresolved parent or a loop. Check source context before correcting it.</li><li><b>Rule broken:</b> an SSM relationship requirement is not met, such as a child assigned outside its parent's UPN.</li><li><b>Check this:</b> a strong pattern needs engineering review. It is not proof that the row is wrong.</li><li><b>Note:</b> information or uncertainty to confirm, such as an unverified milestone scope or optional Item Master migration.</li></ul>
    <p>Read the reason and expected value, not just the color. An external reference may be valid even when its connection cannot be verified from this registry.</p>`},
  {id:'reading',label:'Find and inspect',icon:'search',title:'Focus on the work you own',body:`
    <ol><li>In <b>Audit Findings</b>, search equipment tags or finding text. Use severity chips for a quick scope.</li><li>Open <b>Filters</b> to narrow discipline, building, UPN, L2 milestone, source, topic or check. Remove a filter chip to widen the view again. Dashboard totals follow the active audit filters.</li><li>Open a finding to see why it was flagged, the rule, current and expected values, recommended action and source row.</li><li>Use the relationship diagram for parent, dependency or loop findings. A commissioning loop can combine parent and dependency connections; it need not be a loop of parent tags alone.</li><li>Use <b>Show in hierarchy</b> for context, or Previous and Next to review the filtered list. Click copy-enabled equipment tags to copy them.</li></ol>
    <p>Actions has its own search, milestone and discipline filters. Export choices are separate from these on-screen filters.</p>`},
  {id:'actions',label:'Review and correct',icon:'sliders-horizontal',title:'Work through a set of findings',body:`
    <ol><li>Open <b>Actions</b> and filter to your discipline or L2 milestone. Expand a check to see patterns and their equipment.</li><li>Choose a pattern's <b>Action</b> button, or <b>Action matches</b> for a filtered set.</li><li>Read what is wrong beside each tag. Compare current values with the suggested fix and edit any value as needed. When there is no reliable suggestion, enter a verified value or cancel.</li><li>Select <b>Review changes</b>. The app validates the values and reruns the audit. Review the full current-to-new cell list, including further pages for large batches. No data changes yet. New errors block the batch; use <b>Edit values</b> to adjust a fix.</li><li>Select <b>Apply changes</b> to confirm the entire change list. The confirmation shows cells updated and findings cleared. <b>Cancel</b> before applying leaves the registry unchanged.</li><li>The Dashboard, findings and hierarchy reflect accepted corrections. <b>View all changes</b> opens the correction history, where <b>Undo batch</b> restores the previous draft. Use <b>Updated Registry</b> to download the corrected copy with changed cells highlighted yellow. The original workbook is never overwritten.</li></ol>
    <p>Findings without a supported suggestion remain open. Narrow the set before opening an action if you only want to change specific equipment. Set-aside controls remain available in the Actions list; they do not change registry data.</p>
    <p><b>New Milestones:</b> load your approved project mapping file, switch it on, then select <b>Review replacements</b>. The preview covers all affected registry rows, including rows hidden by filters. Review and apply the old-to-new L1 changes; this does not assign L2 milestones or fill blank parents. Switching it off does not reverse applied edits; use <b>Undo batch</b> to reverse them. Save review includes the local mapping and switch setting.</p>
    <p><b>Cleared in draft</b>, <b>reviewed</b> and <b>changed cells</b> mean different things. None certifies that Exto or the installed equipment has been corrected.</p>`},
  {id:'references',label:'Local references',icon:'file-spreadsheet',title:'Use references to support a correction',body:referenceHelpHtml()},
  {id:'save',label:'Save and resume',icon:'save',title:'Keep a review you can resume',body:`
    <ol><li>Use <b>History</b> to inspect staged cells and review decisions. Revert a cell there, or use <b>Undo</b> to restore a recent batch. A reversal that introduces errors is blocked.</li><li>Select <b>Save review</b> to download a review file. Save again after further changes; the downloaded file does not update itself.</li><li>To resume, open the same original registry and apply the same reference data, then choose <b>Load review</b>.</li><li>The app verifies the registry and reference context, checks the corrections again, and restores compatible progress. A different registry revision is rejected rather than receiving stale edits.</li></ol>
    <p>Changing reference data clears the current undo history. Save first when you need to preserve a checkpoint.</p>
    <p>Review files contain correction values and notes. Share them only with authorized teammates. They are not a live shared session or an automatic merge of two engineers' work.</p>`},
  {id:'checks',label:'Rules and examples',icon:'check-check',title:'Know what each check means',body:`
    <ul><li><b>Registry Integrity:</b> identities, approved values and internal references agree.</li><li><b>SSM SOP:</b> parent, dependency, system and commissioning requirements.</li><li><b>Commissioning Logic:</b> expected power, control and equipment relationships that may need review.</li><li><b>Selected references:</b> additional milestone checks when you supply a project milestone register.</li></ul>
    <p>Missing L1 or L2 milestones are <b>Rule Broken</b>, including blank or placeholder values. Both are required for SSM readiness even though the upload template marks these fields non-gating. An uncertain milestone match remains a separate review finding; do not guess a value just to clear the missing milestone.</p>
    <p>Open <b>Rules</b> to search the plain-language statements and see counts. <b>Example</b> shows a made-up case and the resulting finding.</p>
    <p>A rule switch removes that check from active findings and reports; it does not correct equipment. Rule preferences are remembered on the device. Setting an individual finding aside also changes the counts, not the source data. Use <b>Restore all</b> in Actions to bring set-aside findings back.</p>
    <button class="btn primary guide-rules-link" id="guideOpenRules" type="button">${ic('book-open')}View the rules</button>`},
  {id:'hierarchy',label:'SSM Hierarchy',icon:'list-tree',title:'Inspect placement and connections',body:`
    <p>Explore Building &rarr; Discipline &rarr; System &rarr; equipment. After corrections, this view reflects the working draft.</p>
    <ol><li>Expand branches or search tags, descriptions, parents and dependencies.</li><li>Filter by building, discipline or system. Use <b>Findings only</b> to focus on affected branches.</li><li>Open an equipment row for its metadata, source row, relationships and findings. Organizational headers group equipment and are marked separately.</li><li>Distinguish nesting from dependencies: equipment can sit under one system while relying on equipment in another.</li></ol>
    <p>Seeing a branch in the tree does not validate its commissioning sequence. Read the associated findings before accepting it.</p>`},
  {id:'compare',label:'Compare projects',icon:'square-stack',title:'Compare structure, not identical tag names',body:`
    <ol><li>Load the registry being audited and a completed-project reference.</li><li>Select a UPN. Buildings are ignored for cross-project matching.</li><li>Use the comparison's tabs to inspect system differences and side-by-side equipment placement. Corresponding paired branches expand together.</li><li>Review headers, equipment roles, parent types and dependencies. Use mapping filters and search to narrow the differences.</li><li>Export the comparison for a shareable record.</li></ol>
    <p>A difference is a review prompt, not automatically an error. The completed project may have different scope or its own mistakes. It never changes the audit rules or automatically rewrites your registry.</p>`},
  {id:'report',label:'Exports and teamwork',icon:'file-down',title:'Choose the right export',body:`
    <ul><li><b>Audit report:</b> findings, explanations, rules and equipment context. Choose grouping by milestone or finding level and which levels or checks to include or pre-tick. On-screen filters do not define the export scope.</li><li><b>Updated Registry:</b> a new workbook containing applied draft corrections, with changed cells highlighted yellow. Supported .xlsx exports preserve the original workbook structure and untouched contents. Unsupported formats or conflicting edits are rejected; your original remains unchanged.</li><li><b>Correction Log:</b> before-and-after values and review decisions for traceability.</li><li><b>Tracker:</b> a milestone-by-discipline progress snapshot for allocating work. In-app progress is prefilled; the overall bar follows the manual <b>Milestone actioned?</b> ticks.</li><li><b>Save review:</b> the separate file used to resume work inside the app.</li></ul>
    <p>In the audit report, an equipment block's <b>Actioned</b> tick updates its workbook progress formulas. Workbook ticks do not change Exto or sync back into the app. Share exported files through your team's approved process and coordinate ownership to avoid conflicting copies.</p>
    <p>After approved corrections are uploaded to Exto, export a fresh registry and audit it again to verify the result.</p>`},
  {id:'privacy',label:'Privacy and updates',icon:'lock',title:'Keep control of your data',body:`
    <p>Registry and reference workbooks are processed locally in browser memory. Closing or refreshing clears the session. Nothing is sent to a shared workbook, cloud analysis service or another project.</p>
    <p>Only explicit exports create review files, reports or corrected copies. These can contain sensitive project data, so store and share them appropriately. Rule preferences are saved separately on the device.</p>
    <p>While online, the app checks its own GitHub release channel for updates; fallback checks may run if the first check fails. These requests do not include workbook data. Auditing works offline.</p>
    <p>Click the version number for the changelog or to check again. Download the new versioned HTML, save your review before closing the old copy, then open the new file and reload the registry, references and saved review.</p>`},
];
