import { $, $$, esc } from './core/text.js'
import { APP_VERSION } from './version.js'
import { S } from './state.js'
import { ic } from './ui/icons.js'
import { activateFocusTrap } from './ui/feedback.js'
import { closeDrawer, renderAuditResult, renderComparisonResult, renderDashboard, renderHierarchyResult, renderRules, renderSideNav, renderUpload } from './ui/audit.js'
import { closeUpdateModal, initUpdate } from './update/update.js'

const ruleGuide=()=>'<p>Open Rules in the menu on the left for a searchable, plain-language list of every check the audit runs.</p><div class="guide-note">'+ic('info')+'Checks are grouped by where they come from and what they cover, so they are easy to scan. Once a registry is loaded, each check also shows how many times it fired.</div><button class="btn primary guide-rules-link" id="guideOpenRules" type="button">'+ic('book-open')+'View the rules</button>';
const GUIDE_SECTIONS=[
  {id:'start',label:'Getting started',icon:'upload',title:'Run an audit in three steps',body:'<p>Choose a completed Cx Registry workbook. SSM Audit finds the registry tab on its own, reads it in this browser only, and checks every equipment row.</p><ol><li>Drop an .xlsx or .xls workbook on the upload area, or click <b>Choose workbook</b>.</li><li>Wait a moment — 20,000 rows take about a second.</li><li>Start with <b>Invalid</b>, then <b>Rule broken</b>, then <b>Check this</b>. <b>Notes</b> are for review at your pace.</li></ol><div class="guide-note">'+ic('lock')+'The workbook is never uploaded or saved. Closing or refreshing the page clears it.</div>'},
  {id:'around',label:'Finding your way',icon:'panel-left-open',title:'The workspace',body:'<p>The menu on the left moves between the five views. Counts on each item show what is waiting there.</p><ol><li><b>Dashboard</b> — where an audit lands: totals by level, where the problems sit, milestone readiness, hierarchy health, dependencies, every check that ran, and what the registry is made of. Every number opens the findings list already narrowed to it, and the whole dashboard follows whatever you set in <b>Filters</b> — scope it to one building or discipline and every block recounts.</li><li><b>Audit findings</b> — every issue, most serious first. The level chips are the quick filter; <b>Filters</b> opens one panel for everything else — level, discipline, L2 milestone, UPN, building, source, topic, and individual checks — and whatever you pick shows as chips you can remove one at a time. Deselect a discipline to set it aside — for example, hide Electrical to see which other disciplines list a parent as a dependency.</li><li><b>SSM hierarchy</b> — the registry as a tree from Building down to equipment, with a finding count on every branch. Turn on <b>Findings only</b> to hide clean branches.</li><li><b>Compare projects</b> — line one registry up against a completed one, UPN by UPN.</li><li><b>Rules</b> — every check in plain language, with how many times it fired.</li></ol><p>Use <b>Collapse</b> at the bottom of the menu for more room, or the expand button on any view for a full-screen table.</p>'},
  {id:'severity',label:'What the levels mean',icon:'triangle-alert',title:'Four levels, four kinds of problem',body:'<p>Every finding has one of four levels. They describe what <em>kind</em> of problem it is — not how the registry got here. Most registries you audit are already uploaded, so the levels are about the data itself.</p><ol><li><b>Invalid</b> (red) — the row contradicts the registry or the approved lists: a duplicate tag, a blank or self-referencing parent, a parent that does not exist, a loop, or a UPN, System Name, or discipline that is not in the Rev21 upload template. On a fresh upload these are the rows Exto would reject; on an uploaded registry they are the rows that cannot be right.</li><li><b>Rule broken</b> (orange) — the data is valid, but it breaks an SSM SOP rule: a parent in another UPN, a dependency that cannot be found, an instrument or LCP nested off its UPN, a VESDA with no fire alarm panel.</li><li><b>Check this</b> (amber) — a strong pattern says something is off and an engineer should look. Most commissioning-logic and nesting checks live here.</li><li><b>Note</b> (grey-blue) — worth knowing, not necessarily wrong: a same-system dependency in a mechanical discipline, a milestone not yet assigned, an Item Master still on a site prefix.</li></ol>'},

  {id:'reading',label:'Reading a finding',icon:'file-text',title:'Every finding explains itself',body:'<p>Click any row to open it. Top to bottom you will see:</p><ol><li><b>Why this was flagged</b> — the plain-language reason, written for someone picking this up cold.</li><li><b>What must be true</b> — the rule behind it, and where the rule comes from (SSM SOP, Registry Integrity, or Commissioning Logic).</li><li><b>The relationship</b> — for parent, dependency, and loop findings, a small diagram that labels which tag is this equipment, which is its parent or dependency, and the order of a loop.</li><li><b>Found / Expected</b> and <b>What to do</b> — the specific fix.</li><li><b>The registry row</b> — description, parent, UPN, System Name, milestones, Item Master, dependencies.</li></ol><p><b>Show in hierarchy</b> jumps to that equipment in the tree. <b>Previous</b> and <b>Next</b> walk the current filtered list.</p>'},
  {id:'checks',label:'What is checked',icon:'check-check',title:'Three sources of truth',body:'<p>Checks come from three places, and each finding says which.</p><ol><li><b>Registry Integrity</b> — the registry agrees with itself and with the approved Rev21 lists: one row per tag, tags that are codes rather than typed descriptions, resolvable parents, UPNs and System Names from the approved values, I&amp;C rows on the approved controls discipline, Dependency Project only when a dependency really is external, and a note on classifications not in the Rev21 dropdown so site-specific codes can be reviewed.</li><li><b>SSM SOP</b> — how equipment nests and depends: a child stays in its parent\'s UPN, discipline, and building; anything crossing them is a dependency, not a parent; instruments nest under equipment in the UPN their tag carries; a VFD sits under what it drives with its panel and PLC as dependencies; LCPs sit with their skid; control valves and room sensors sit under the equipment they serve; headers carry a Blank Item Master, no dependencies, and are never themselves a dependency; every system has a row at its top; L2 milestones name their UPN; Item Masters use the VF standard.</li><li><b>Commissioning Logic</b> — expected relationships: driven and control equipment trace back to power, RIOs name their controller, heat trace follows its transformer, VESDA depends on its fire alarm panel.</li></ol>'+ruleGuide()},
  {id:'hierarchy',label:'SSM hierarchy',icon:'list-tree',title:'Explore the registry as a tree',body:'<p>Building &rarr; Discipline &rarr; System Name &rarr; equipment, exactly as uploaded. Nothing is silently repaired.</p><ol><li>Search tags, descriptions, parents, or dependencies; matches are highlighted and their branches open.</li><li>Filter to a building, discipline, or system. <b>Findings only</b> collapses to branches that have something to fix.</li><li>Rows used as organizational headers (a Blank Item Master that other equipment nests under) are marked as headers.</li><li>Open any equipment for its metadata, relationships, source row, and findings.</li></ol>'},
  {id:'report',label:'The Excel report',icon:'file-down',title:'Export a report you can work from',body:'<p><b>Export</b> in the menu creates a workbook built for actioning, not just reading:</p><ol><li><b>Dashboard</b> — totals, and a progress bar with a live percentage for every L2 phase.</li><li><b>Index</b> — one row per phase, each linked to its own tab; every tab links back.</li><li><b>One tab per L2 phase</b> — every piece of equipment in that phase as an indented tree with its nest level, one line per finding with the reason and what to do, and an <b>Actioned</b> column. Type <b>Y</b> there and the Index and Dashboard update.</li><li><b>All Findings</b> and <b>Rules</b> — the flat list and the plain-language rulebook.</li></ol><div class="guide-note">'+ic('info')+'Filters in the app do not change the report — it always contains everything.</div>'},
  {id:'compare',label:'Project comparison',icon:'square-stack',title:'Compare with a completed project',body:'<p>Audit a registry as usual, then line it up against a completed project by UPN. Buildings are ignored so different sites do not create false differences.</p><ol><li>Choose the registry to audit and a completed project as the reference.</li><li>Pick a UPN to compare nesting, headers, dependencies, and I&amp;C placement.</li><li>Treat differences as prompts. The completed project is precedent, not a rule.</li></ol><div class="guide-note">'+ic('lock')+'Both workbooks stay in this browser for the session only. The reference never changes the checks.</div>'},
  {id:'privacy',label:'Privacy',icon:'lock',title:'The registry stays on this device',body:'<p>Nothing you load is uploaded, saved, or used to learn future behavior. The only network request is one anonymous check for a newer SSM Audit release when the page opens.</p>'},
];
let activeGuide='start';
let guideOpener=null;
let guideTrapCleanup=null;

function go(screen){S.screen=screen;if(screen==='dashboard')renderDashboard(go);else if(screen==='audit')renderAuditResult(go);else if(screen==='hierarchy')renderHierarchyResult(go);else if(screen==='compare')renderComparisonResult(go);else if(screen==='rules')renderRules(go);else renderUpload(go);renderSideNav(go);}
function renderGuide(){
  $('#guideNav').innerHTML=GUIDE_SECTIONS.map(section=>`<button type="button" class="${section.id===activeGuide?'active':''}" data-guide="${section.id}">${ic(section.icon)}${esc(section.label)}</button>`).join('');
  const section=GUIDE_SECTIONS.find(item=>item.id===activeGuide)||GUIDE_SECTIONS[0];$('#guideBody').innerHTML=`<div class="guide-copy"><span class="eyebrow">SSM Audit Guide</span><h3>${esc(section.title)}</h3>${section.body}</div>`;
  $$('[data-guide]').forEach(button=>button.onclick=()=>{activeGuide=button.dataset.guide;renderGuide();});
  const openRules=$('#guideOpenRules');if(openRules)openRules.onclick=()=>{closeGuide();S.homeMode='rules';go('rules');};
}
function openGuide(){guideOpener=document.activeElement;renderGuide();const modal=$('#guideModal');modal.hidden=false;modal.classList.add('show');modal.setAttribute('aria-hidden','false');guideTrapCleanup?.();guideTrapCleanup=activateFocusTrap(modal,closeGuide);requestAnimationFrame(()=>$('#guideClose').focus());}
function closeGuide(){const modal=$('#guideModal');if(!modal.classList.contains('show'))return;guideTrapCleanup?.();guideTrapCleanup=null;modal.classList.remove('show');modal.hidden=true;modal.setAttribute('aria-hidden','true');const opener=guideOpener;guideOpener=null;if(opener&&document.contains(opener)&&typeof opener.focus==='function')opener.focus();}

function init(){
  $('#brandmark').innerHTML=ic('zap');$('#headerGuide').innerHTML=ic('book-open')+'<span>Guide</span>';$('#headerGuide').onclick=openGuide;
  $('#versionLink').textContent=`v${APP_VERSION}`;$('#guideClose').classList.add('xbtn');$('#guideClose').innerHTML=ic('x');$('#guideClose').onclick=closeGuide;
  $('#guideModal').onclick=event=>{if(event.target===$('#guideModal'))closeGuide();};document.addEventListener('ssm-audit:guide',openGuide);
  document.addEventListener('ssm-audit:navigate',event=>go(event.detail&&event.detail.screen||'upload'));
  $('#drawerClose').innerHTML=ic('x');$('#drawerClose').onclick=closeDrawer;$('#drawerBack').onclick=event=>{if(event.target===$('#drawerBack'))closeDrawer();};
  document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;if($('#drawerBack').classList.contains('show'))closeDrawer();else if($('#guideModal').classList.contains('show'))closeGuide();else if($('#updateModal').classList.contains('show'))closeUpdateModal();});
  /* Narrow screens: the fixed version badge floats over content, so it moves
     into the topbar actions and back again as the window crosses 900px. */
  const badgeHome=$('#versionLink').parentElement,mq=window.matchMedia('(max-width:900px)');
  const placeBadge=()=>{const badge=$('#versionLink'),actions=$('.top-actions');if(!badge||!actions)return;if(mq.matches){if(badge.parentElement!==actions)actions.insertBefore(badge,actions.firstChild);}else if(badge.parentElement!==badgeHome)badgeHome.appendChild(badge);};
  placeBadge();if(typeof mq.addEventListener==='function')mq.addEventListener('change',placeBadge);
  initUpdate();go('upload');
}

init();
